"""Hook installer for Claude Comms PostToolUse notification hook.

Detects platform (Unix/WSL vs Windows), generates the appropriate hook script,
installs it to ~/.claude/hooks/, and configures ~/.claude/settings.json with the
PostToolUse hook entry.

Exports: install_hook, uninstall_hook
"""

from __future__ import annotations

import json
import platform
import stat
import sys
from pathlib import Path
from typing import Any

from claude_comms.config import load_config


# --- Path helpers ---


def _claude_hooks_dir() -> Path:
    """Return ~/.claude/hooks/ directory."""
    return Path.home() / ".claude" / "hooks"


def _claude_settings_path() -> Path:
    """Return ~/.claude/settings.json path."""
    return Path.home() / ".claude" / "settings.json"


def _notification_dir() -> Path:
    """Return ~/.claude-comms/notifications/ directory."""
    return Path.home() / ".claude-comms" / "notifications"


def _is_windows() -> bool:
    """Detect if running on native Windows (not WSL)."""
    return sys.platform == "win32" or (platform.system() == "Windows")


def _hook_script_name(participant_key: str) -> str:
    """Return the hook script filename for a given participant key."""
    ext = ".cmd" if _is_windows() else ".sh"
    return f"claude-comms-notify-{participant_key}{ext}"


def _hook_script_path(participant_key: str) -> Path:
    """Return full path to the hook script."""
    return _claude_hooks_dir() / _hook_script_name(participant_key)


# --- Script generation ---


DEFAULT_BASE_URL = "http://localhost:9920"

# The python formatter is shared verbatim between the generated bash hook and
# the test harness. It reads the daemon's JSON response (``{"cues": [...]}``)
# from stdin and emits the PostToolUse additionalContext. CRITICAL: no message
# body is ever interpolated into this SOURCE — everything is parsed as JSON and
# used as data, so a body with newlines, quotes, unicode, ``$(...)`` or
# backticks is inert (can never break the hook or inject shell/python code).
_PY_FORMATTER = r"""
import json, sys
try:
    data = json.load(sys.stdin)
except Exception:
    raise SystemExit(0)
cues = data.get("cues") or []
count = len(cues)
recent = cues[-5:]
parts = []
for d in recent:
    if not isinstance(d, dict):
        continue
    conv = d.get("conversation", "?")
    sender = d.get("sender_name") or d.get("sender_key", "?")
    body = (d.get("body", "") or "")[:120]
    parts.append("\n  #" + str(conv) + " @" + str(sender) + ": " + str(body))
summary = "".join(parts)
if count > 5:
    summary += "\n  ... and " + str(count - 5) + " more message(s)"
if not summary:
    raise SystemExit(0)
ctx = "\U0001f4ec New messages:" + summary + "\n\n(Use comms_read for full history, comms_send to reply)"
print(json.dumps(dict(hookSpecificOutput=dict(hookEventName="PostToolUse", additionalContext=ctx))))
"""


def _generate_unix_script(
    participant_key: str, base_url: str = DEFAULT_BASE_URL
) -> str:
    """Generate the bash hook script content with key + daemon URL baked in.

    The hook FETCHES queued cues from the daemon over HTTP
    (``<base_url>/api/notifications/<key>``) — the endpoint drains them
    server-side — instead of reading a local file, so it works against a
    REMOTE daemon. The HTTP response is piped to a single ``python3 -c`` pass
    that parses the JSON and formats additionalContext; no body text is ever
    interpolated into the python source (injection/crash-safe).
    """
    endpoint = f"{base_url.rstrip('/')}/api/notifications/{participant_key}"

    return f"""\
#!/bin/bash
# Claude Comms PostToolUse notification hook
# Participant key: {participant_key}
# Daemon URL: {base_url}
# Auto-generated by claude-comms — do not edit manually

# 1. Drain stdin (required — hook hangs if stdin not consumed)
cat > /dev/null

# 2. Fetch queued cues from the daemon (drains server-side). Fail soft: any
# curl error / unreachable daemon / empty response exits 0 silently.
RESP=$(curl -fsS --max-time 3 "{endpoint}" 2>/dev/null)
[ -n "$RESP" ] || exit 0

# 3. Format + emit additionalContext in ONE python pass. The response JSON is
# fed on stdin and parsed there, so a body containing newlines, quotes,
# unicode, $(...) or backticks is inert — never interpolated into the source.
printf '%s' "$RESP" | python3 -c '{_PY_FORMATTER}'
"""


def _generate_windows_script(
    participant_key: str, base_url: str = DEFAULT_BASE_URL
) -> str:
    """Generate the Windows .cmd hook script with key + daemon URL baked in.

    Like the Unix script, this FETCHES cues over HTTP (the endpoint drains
    them server-side) and formats them in PowerShell. Null-safe: an
    unreachable daemon / empty response exits 0.
    """
    endpoint = f"{base_url.rstrip('/')}/api/notifications/{participant_key}"

    # On Windows, use a PowerShell one-liner wrapped in cmd. All formatting
    # happens on parsed JSON objects, so message bodies are inert data.
    return f"""\
@echo off
REM Claude Comms PostToolUse notification hook
REM Participant key: {participant_key}
REM Daemon URL: {base_url}
REM Auto-generated by claude-comms — do not edit manually

REM 1. Drain stdin (required — hook hangs if stdin not consumed)
more > nul 2>&1

REM 2-3. Fetch cues over HTTP (drains server-side) and format via PowerShell
powershell -NoProfile -Command ^
  "$ErrorActionPreference = 'Stop';" ^
  "try {{ $resp = Invoke-RestMethod -Uri '{endpoint}' -TimeoutSec 3 }} catch {{ exit 0 }};" ^
  "if (-not $resp) {{ exit 0 }};" ^
  "$cues = @($resp.cues);" ^
  "$count = $cues.Count;" ^
  "if ($count -eq 0) {{ exit 0 }};" ^
  "$recent = $cues | Select-Object -Last 5;" ^
  "$summary = '';" ^
  "foreach ($m in $recent) {{" ^
  "  $conv = if ($m.conversation) {{ $m.conversation }} else {{ '?' }};" ^
  "  $sender = if ($m.sender_name) {{ $m.sender_name }} elseif ($m.sender_key) {{ $m.sender_key }} else {{ '?' }};" ^
  "  $b = [string]$m.body;" ^
  "  $body = $b.Substring(0, [Math]::Min(120, $b.Length));" ^
  "  $summary += \"`n  #$conv @$sender`: $body\";" ^
  "}};" ^
  "if ($count -gt 5) {{ $summary += \"`n  ... and $($count - 5) more message(s)\" }};" ^
  "$ctx = [char]0x1F4EC + ' New messages:' + $summary + \"`n`n(Use comms_read for full history, comms_send to reply)\";" ^
  "$out = @{{ hookSpecificOutput = @{{ hookEventName = 'PostToolUse'; additionalContext = $ctx }} }};" ^
  "Write-Output ($out | ConvertTo-Json -Compress)"
"""


def generate_hook_script(participant_key: str, base_url: str = DEFAULT_BASE_URL) -> str:
    """Generate the hook script content for the current platform.

    Args:
        participant_key: The participant identity key to bake into the script.
        base_url: Base URL of the claude-comms daemon the hook fetches cues
            from. Pass a remote address for cross-machine delivery.

    Returns:
        The script content as a string.
    """
    if _is_windows():
        return _generate_windows_script(participant_key, base_url)
    return _generate_unix_script(participant_key, base_url)


# --- Settings.json manipulation ---


def _load_settings(path: Path) -> dict[str, Any]:
    """Load Claude Code settings.json, returning empty dict if missing."""
    if path.exists():
        with open(path) as f:
            try:
                return json.load(f)
            except json.JSONDecodeError:
                return {}
    return {}


def _save_settings(settings: dict[str, Any], path: Path) -> None:
    """Save Claude Code settings.json with pretty formatting."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as f:
        json.dump(settings, f, indent=2)
        f.write("\n")


def _hook_command_path(participant_key: str) -> str:
    """Return the absolute path string for the hook command."""
    return str(_hook_script_path(participant_key))


def _build_hook_entry(participant_key: str) -> dict[str, Any]:
    """Build a single PostToolUse hook entry for settings.json."""
    return {
        "matcher": "",
        "hooks": [
            {
                "type": "command",
                "command": _hook_command_path(participant_key),
                "timeout": 5,
            }
        ],
    }


def _add_hook_to_settings(
    settings: dict[str, Any], participant_key: str
) -> dict[str, Any]:
    """Add the PostToolUse hook entry to settings, avoiding duplicates.

    If a claude-comms hook already exists (detected by command path containing
    'claude-comms-notify'), it is replaced. Otherwise, the new entry is appended.
    """
    hooks = settings.setdefault("hooks", {})
    post_tool_use = hooks.setdefault("PostToolUse", [])

    # Remove any existing claude-comms hook entries
    post_tool_use[:] = [
        entry for entry in post_tool_use if not _is_claude_comms_hook_entry(entry)
    ]

    # Add the new entry
    post_tool_use.append(_build_hook_entry(participant_key))

    return settings


def _remove_hook_from_settings(settings: dict[str, Any]) -> dict[str, Any]:
    """Remove claude-comms hook entries from settings."""
    hooks = settings.get("hooks", {})
    post_tool_use = hooks.get("PostToolUse", [])

    if post_tool_use:
        hooks["PostToolUse"] = [
            entry for entry in post_tool_use if not _is_claude_comms_hook_entry(entry)
        ]

        # Clean up empty structures
        if not hooks["PostToolUse"]:
            del hooks["PostToolUse"]
        if not hooks:
            del settings["hooks"]

    return settings


def _is_claude_comms_hook_entry(entry: dict[str, Any]) -> bool:
    """Check if a hook entry belongs to claude-comms."""
    for hook in entry.get("hooks", []):
        cmd = hook.get("command", "")
        if "claude-comms-notify" in cmd:
            return True
    return False


# --- Public API ---


def install_hook(
    participant_key: str | None = None,
    base_url: str = DEFAULT_BASE_URL,
    config_path: Path | None = None,
) -> dict[str, Any]:
    """Install the Claude Comms notification hook.

    1. Checks notifications.hook_enabled config — skips if False
    2. Loads participant key from config if not provided
    3. Generates platform-appropriate hook script (fetches cues from base_url)
    4. Installs script to ~/.claude/hooks/
    5. Adds PostToolUse entry to ~/.claude/settings.json
    6. Creates notification directory

    Args:
        participant_key: Override the participant key (default: from config).
        base_url: Base URL of the daemon the hook fetches cues from. Pass a
            remote address (e.g. http://daemon-host:9920) for cross-machine
            delivery.
        config_path: Override the config file path (for testing).

    Returns:
        Dict with 'script_path' and 'settings_path' keys on success,
        or {'skipped': True, 'reason': ...} when hook_enabled is False.

    Raises:
        ValueError: If no participant key is available.
        OSError: If file system operations fail.
    """
    # Resolve participant key and check hook_enabled config
    config = load_config(config_path)

    if not config.get("notifications", {}).get("hook_enabled", True):
        return {"skipped": True, "reason": "hook_enabled is False in config"}

    if participant_key is None:
        participant_key = config["identity"]["key"]
        if not participant_key:
            raise ValueError(
                "No participant key found in config. Run 'claude-comms init' first."
            )

    if not isinstance(participant_key, str) or not participant_key.strip():
        raise ValueError("participant_key must be a non-empty string.")

    # Generate and install hook script
    script_content = generate_hook_script(participant_key, base_url)
    script_path = _hook_script_path(participant_key)
    try:
        script_path.parent.mkdir(parents=True, exist_ok=True)
        script_path.write_text(script_content)
    except OSError as exc:
        raise OSError(f"Failed to write hook script to {script_path}: {exc}") from exc

    # Make executable on Unix
    if not _is_windows():
        try:
            script_path.chmod(
                script_path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH
            )
        except OSError:
            pass  # Non-fatal: script may still work without explicit +x on some systems

    # Create notification directory
    try:
        _notification_dir().mkdir(parents=True, exist_ok=True)
    except OSError as exc:
        raise OSError(f"Failed to create notification directory: {exc}") from exc

    # Update Claude Code settings.json
    settings_path = _claude_settings_path()
    try:
        settings = _load_settings(settings_path)
        settings = _add_hook_to_settings(settings, participant_key)
        _save_settings(settings, settings_path)
    except (OSError, json.JSONDecodeError) as exc:
        raise OSError(f"Failed to update settings at {settings_path}: {exc}") from exc

    return {
        "script_path": script_path,
        "settings_path": settings_path,
    }


def uninstall_hook(
    participant_key: str | None = None,
    config_path: Path | None = None,
) -> dict[str, bool]:
    """Uninstall the Claude Comms notification hook.

    1. Removes hook script from ~/.claude/hooks/
    2. Removes PostToolUse entry from ~/.claude/settings.json

    Args:
        participant_key: Override the participant key (default: from config).
        config_path: Override the config file path (for testing).

    Returns:
        Dict with 'script_removed' and 'settings_updated' booleans.
    """
    # Resolve participant key
    if participant_key is None:
        config = load_config(config_path)
        participant_key = config["identity"]["key"]

    result = {"script_removed": False, "settings_updated": False}

    if not participant_key:
        return result

    # Remove hook script
    script_path = _hook_script_path(participant_key)
    try:
        if script_path.exists():
            script_path.unlink()
            result["script_removed"] = True
    except OSError as exc:
        # Log but don't fail — settings cleanup can still proceed
        import logging

        logging.getLogger(__name__).warning(
            "Could not remove hook script %s: %s", script_path, exc
        )

    # Update Claude Code settings.json
    settings_path = _claude_settings_path()
    try:
        if settings_path.exists():
            settings = _load_settings(settings_path)
            settings = _remove_hook_from_settings(settings)
            _save_settings(settings, settings_path)
            result["settings_updated"] = True
    except (OSError, json.JSONDecodeError) as exc:
        import logging

        logging.getLogger(__name__).warning(
            "Could not update settings %s: %s", settings_path, exc
        )

    return result
