"""Hook installer for Claude Comms PostToolUse notification hook.

Detects platform (Unix/WSL vs Windows), generates the appropriate hook script,
installs it to ~/.claude/hooks/, and configures ~/.claude/settings.json with the
PostToolUse hook entry.

Exports: install_hook, uninstall_hook
"""

from __future__ import annotations

import json
import os
import platform
import stat
import sys
from pathlib import Path
from typing import Any

from claude_comms.config import load_config


# --- Path helpers ---

def _claude_hooks_dir() -> Path:
    """Return ~/.claude/hooks/ directory."""
    return Path.home() / ".claude" / "hooks"


def _claude_settings_path() -> Path:
    """Return ~/.claude/settings.json path."""
    return Path.home() / ".claude" / "settings.json"


def _notification_dir() -> Path:
    """Return ~/.claude-comms/notifications/ directory."""
    return Path.home() / ".claude-comms" / "notifications"


def _is_windows() -> bool:
    """Detect if running on native Windows (not WSL)."""
    return sys.platform == "win32" or (
        platform.system() == "Windows"
    )


def _hook_script_name(participant_key: str) -> str:
    """Return the hook script filename for a given participant key."""
    ext = ".cmd" if _is_windows() else ".sh"
    return f"claude-comms-notify-{participant_key}{ext}"


def _hook_script_path(participant_key: str) -> Path:
    """Return full path to the hook script."""
    return _claude_hooks_dir() / _hook_script_name(participant_key)


# --- Script generation ---

def _generate_unix_script(participant_key: str) -> str:
    """Generate the bash hook script content with the participant key baked in."""
    notif_dir = _notification_dir()
    notif_file = notif_dir / f"{participant_key}.jsonl"

    return f"""\
#!/bin/bash
# Claude Comms PostToolUse notification hook
# Participant key: {participant_key}
# Auto-generated by claude-comms — do not edit manually

# 1. Drain stdin (required — hook hangs if stdin not consumed)
cat > /dev/null

# 2. Check notification file exists and has content
NOTIF_FILE="{notif_file}"
[ -s "$NOTIF_FILE" ] || exit 0

# 3. Read and truncate notification file atomically
CONTENT=$(cat "$NOTIF_FILE")
> "$NOTIF_FILE"

# 4. Format messages for context injection
# Take up to 5 most recent lines
MESSAGES=$(echo "$CONTENT" | tail -n 5)
COUNT=$(echo "$CONTENT" | wc -l | tr -d ' ')

# Build summary from JSONL lines
SUMMARY=""
while IFS= read -r line; do
    CONV=$(echo "$line" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('conversation','?'))" 2>/dev/null)
    SENDER=$(echo "$line" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('sender_name','') or d.get('sender_key','?'))" 2>/dev/null)
    BODY=$(echo "$line" | python3 -c "import sys,json; b=json.load(sys.stdin).get('body',''); print(b[:120])" 2>/dev/null)
    if [ -n "$CONV" ] && [ -n "$BODY" ]; then
        SUMMARY="$SUMMARY\\n  #$CONV @$SENDER: $BODY"
    fi
done <<< "$MESSAGES"

if [ "$COUNT" -gt 5 ]; then
    SUMMARY="$SUMMARY\\n  ... and $(( COUNT - 5 )) more message(s)"
fi

# 5. Output JSON with additionalContext
python3 -c "
import json, sys
ctx = '\\U0001f4ec New messages:' + '$SUMMARY' + '\\n\\n(Use comms_read for full history, comms_send to reply)'
print(json.dumps({{
    'hookSpecificOutput': {{
        'hookEventName': 'PostToolUse',
        'additionalContext': ctx
    }}
}}))
"
"""


def _generate_windows_script(participant_key: str) -> str:
    """Generate the Windows .cmd hook script with the participant key baked in."""
    notif_dir = _notification_dir()
    notif_file = notif_dir / f"{participant_key}.jsonl"

    # On Windows, use a PowerShell one-liner wrapped in cmd
    return f"""\
@echo off
REM Claude Comms PostToolUse notification hook
REM Participant key: {participant_key}
REM Auto-generated by claude-comms — do not edit manually

REM 1. Drain stdin (required — hook hangs if stdin not consumed)
more > nul 2>&1

REM 2. Check notification file exists and has content
set "NOTIF_FILE={notif_file}"
if not exist "%NOTIF_FILE%" exit /b 0
for %%A in ("%NOTIF_FILE%") do if %%~zA==0 exit /b 0

REM 3-5. Read, truncate, and format via PowerShell
powershell -NoProfile -Command ^
  "$f = '{notif_file}';" ^
  "$lines = Get-Content $f -ErrorAction SilentlyContinue;" ^
  "if (-not $lines) {{ exit 0 }};" ^
  "Set-Content $f -Value '' -NoNewline;" ^
  "$recent = $lines | Select-Object -Last 5;" ^
  "$summary = '';" ^
  "foreach ($ln in $recent) {{" ^
  "  try {{ $m = $ln | ConvertFrom-Json;" ^
  "    $conv = $m.conversation;" ^
  "    $sender = if ($m.sender_name) {{ $m.sender_name }} else {{ $m.sender_key }};" ^
  "    $body = $m.body.Substring(0, [Math]::Min(120, $m.body.Length));" ^
  "    $summary += \"`n  #$conv @$sender`: $body\";" ^
  "  }} catch {{}};" ^
  "}};" ^
  "if ($lines.Count -gt 5) {{ $summary += \"`n  ... and $($lines.Count - 5) more message(s)\" }};" ^
  "$ctx = [char]0x1F4EC + ' New messages:' + $summary + \"`n`n(Use comms_read for full history, comms_send to reply)\";" ^
  "$out = @{{ hookSpecificOutput = @{{ hookEventName = 'PostToolUse'; additionalContext = $ctx }} }};" ^
  "Write-Output ($out | ConvertTo-Json -Compress)"
"""


def generate_hook_script(participant_key: str) -> str:
    """Generate the hook script content for the current platform.

    Args:
        participant_key: The participant identity key to bake into the script.

    Returns:
        The script content as a string.
    """
    if _is_windows():
        return _generate_windows_script(participant_key)
    return _generate_unix_script(participant_key)


# --- Settings.json manipulation ---

def _load_settings(path: Path) -> dict[str, Any]:
    """Load Claude Code settings.json, returning empty dict if missing."""
    if path.exists():
        with open(path) as f:
            try:
                return json.load(f)
            except json.JSONDecodeError:
                return {}
    return {}


def _save_settings(settings: dict[str, Any], path: Path) -> None:
    """Save Claude Code settings.json with pretty formatting."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as f:
        json.dump(settings, f, indent=2)
        f.write("\n")


def _hook_command_path(participant_key: str) -> str:
    """Return the absolute path string for the hook command."""
    return str(_hook_script_path(participant_key))


def _build_hook_entry(participant_key: str) -> dict[str, Any]:
    """Build a single PostToolUse hook entry for settings.json."""
    return {
        "matcher": "",
        "hooks": [
            {
                "type": "command",
                "command": _hook_command_path(participant_key),
                "timeout": 5,
            }
        ],
    }


def _add_hook_to_settings(settings: dict[str, Any], participant_key: str) -> dict[str, Any]:
    """Add the PostToolUse hook entry to settings, avoiding duplicates.

    If a claude-comms hook already exists (detected by command path containing
    'claude-comms-notify'), it is replaced. Otherwise, the new entry is appended.
    """
    hooks = settings.setdefault("hooks", {})
    post_tool_use = hooks.setdefault("PostToolUse", [])

    # Remove any existing claude-comms hook entries
    post_tool_use[:] = [
        entry for entry in post_tool_use
        if not _is_claude_comms_hook_entry(entry)
    ]

    # Add the new entry
    post_tool_use.append(_build_hook_entry(participant_key))

    return settings


def _remove_hook_from_settings(settings: dict[str, Any]) -> dict[str, Any]:
    """Remove claude-comms hook entries from settings."""
    hooks = settings.get("hooks", {})
    post_tool_use = hooks.get("PostToolUse", [])

    if post_tool_use:
        hooks["PostToolUse"] = [
            entry for entry in post_tool_use
            if not _is_claude_comms_hook_entry(entry)
        ]

        # Clean up empty structures
        if not hooks["PostToolUse"]:
            del hooks["PostToolUse"]
        if not hooks:
            del settings["hooks"]

    return settings


def _is_claude_comms_hook_entry(entry: dict[str, Any]) -> bool:
    """Check if a hook entry belongs to claude-comms."""
    for hook in entry.get("hooks", []):
        cmd = hook.get("command", "")
        if "claude-comms-notify" in cmd:
            return True
    return False


# --- Public API ---

def install_hook(
    participant_key: str | None = None,
    config_path: Path | None = None,
) -> dict[str, Path]:
    """Install the Claude Comms notification hook.

    1. Loads participant key from config if not provided
    2. Generates platform-appropriate hook script
    3. Installs script to ~/.claude/hooks/
    4. Adds PostToolUse entry to ~/.claude/settings.json
    5. Creates notification directory

    Args:
        participant_key: Override the participant key (default: from config).
        config_path: Override the config file path (for testing).

    Returns:
        Dict with 'script_path' and 'settings_path' keys.
    """
    # Resolve participant key
    if participant_key is None:
        config = load_config(config_path)
        participant_key = config["identity"]["key"]
        if not participant_key:
            raise ValueError(
                "No participant key found in config. Run 'claude-comms init' first."
            )

    # Generate and install hook script
    script_content = generate_hook_script(participant_key)
    script_path = _hook_script_path(participant_key)
    script_path.parent.mkdir(parents=True, exist_ok=True)
    script_path.write_text(script_content)

    # Make executable on Unix
    if not _is_windows():
        script_path.chmod(
            script_path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH
        )

    # Create notification directory
    _notification_dir().mkdir(parents=True, exist_ok=True)

    # Update Claude Code settings.json
    settings_path = _claude_settings_path()
    settings = _load_settings(settings_path)
    settings = _add_hook_to_settings(settings, participant_key)
    _save_settings(settings, settings_path)

    return {
        "script_path": script_path,
        "settings_path": settings_path,
    }


def uninstall_hook(
    participant_key: str | None = None,
    config_path: Path | None = None,
) -> dict[str, bool]:
    """Uninstall the Claude Comms notification hook.

    1. Removes hook script from ~/.claude/hooks/
    2. Removes PostToolUse entry from ~/.claude/settings.json

    Args:
        participant_key: Override the participant key (default: from config).
        config_path: Override the config file path (for testing).

    Returns:
        Dict with 'script_removed' and 'settings_updated' booleans.
    """
    # Resolve participant key
    if participant_key is None:
        config = load_config(config_path)
        participant_key = config["identity"]["key"]

    result = {"script_removed": False, "settings_updated": False}

    # Remove hook script
    script_path = _hook_script_path(participant_key)
    if script_path.exists():
        script_path.unlink()
        result["script_removed"] = True

    # Update Claude Code settings.json
    settings_path = _claude_settings_path()
    if settings_path.exists():
        settings = _load_settings(settings_path)
        settings = _remove_hook_from_settings(settings)
        _save_settings(settings, settings_path)
        result["settings_updated"] = True

    return result
