@echo off
REM Claude Comms PostToolUse notification hook — Windows template
REM Participant key: %%PARTICIPANT_KEY%%
REM Auto-generated by claude-comms — do not edit manually
REM
REM This is the template file. The hook_installer.py generates a copy of this
REM with %%PARTICIPANT_KEY%% and %%NOTIF_FILE%% replaced, installed to
REM ~/.claude/hooks/claude-comms-notify-{key}.cmd

REM 1. Drain stdin (required — hook hangs if stdin not consumed)
more > nul 2>&1

REM 2. Check notification file exists and has content
set "NOTIF_FILE=%USERPROFILE%\.claude-comms\notifications\%%PARTICIPANT_KEY%%.jsonl"
if not exist "%NOTIF_FILE%" exit /b 0
for %%A in ("%NOTIF_FILE%") do if %%~zA==0 exit /b 0

REM 3-5. Read, truncate, and format via PowerShell
powershell -NoProfile -Command ^
  "$f = '%NOTIF_FILE%';" ^
  "$lines = Get-Content $f -ErrorAction SilentlyContinue;" ^
  "if (-not $lines) { exit 0 };" ^
  "Set-Content $f -Value '' -NoNewline;" ^
  "$recent = $lines | Select-Object -Last 5;" ^
  "$summary = '';" ^
  "foreach ($ln in $recent) {" ^
  "  try { $m = $ln | ConvertFrom-Json;" ^
  "    $conv = $m.conversation;" ^
  "    $sender = if ($m.sender_name) { $m.sender_name } else { $m.sender_key };" ^
  "    $body = $m.body.Substring(0, [Math]::Min(120, $m.body.Length));" ^
  "    $summary += \"`n  #$conv @$sender`: $body\";" ^
  "  } catch {};" ^
  "};" ^
  "if ($lines.Count -gt 5) { $summary += \"`n  ... and $($lines.Count - 5) more message(s)\" };" ^
  "$ctx = [char]0x1F4EC + ' New messages:' + $summary + \"`n`n(Use comms_read for full history, comms_send to reply)\";" ^
  "$out = @{ hookSpecificOutput = @{ hookEventName = 'PostToolUse'; additionalContext = $ctx } };" ^
  "Write-Output ($out | ConvertTo-Json -Compress)"
