#!/bin/bash
# Claude Comms PostToolUse notification hook — Unix/WSL template
# Participant key: %%PARTICIPANT_KEY%%
# Auto-generated by claude-comms — do not edit manually
#
# This is the template file. The hook_installer.py generates a copy of this
# with %%PARTICIPANT_KEY%% and %%NOTIF_FILE%% replaced, installed to
# ~/.claude/hooks/claude-comms-notify-{key}.sh

# 1. Drain stdin (required — hook hangs if stdin not consumed)
cat > /dev/null

# 2. Check notification file exists and has content
NOTIF_FILE="$HOME/.claude-comms/notifications/%%PARTICIPANT_KEY%%.jsonl"
[ -s "$NOTIF_FILE" ] || exit 0

# 3. Read and truncate notification file atomically
CONTENT=$(cat "$NOTIF_FILE")
> "$NOTIF_FILE"

# 4. Format messages for context injection
# Take up to 5 most recent lines
MESSAGES=$(echo "$CONTENT" | tail -n 5)
COUNT=$(echo "$CONTENT" | wc -l | tr -d ' ')

# Build summary from JSONL lines
SUMMARY=""
while IFS= read -r line; do
    CONV=$(echo "$line" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('conversation','?'))" 2>/dev/null)
    SENDER=$(echo "$line" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('sender_name','') or d.get('sender_key','?'))" 2>/dev/null)
    BODY=$(echo "$line" | python3 -c "import sys,json; b=json.load(sys.stdin).get('body',''); print(b[:120])" 2>/dev/null)
    if [ -n "$CONV" ] && [ -n "$BODY" ]; then
        SUMMARY="$SUMMARY\n  #$CONV @$SENDER: $BODY"
    fi
done <<< "$MESSAGES"

if [ "$COUNT" -gt 5 ]; then
    SUMMARY="$SUMMARY\n  ... and $(( COUNT - 5 )) more message(s)"
fi

# 5. Output JSON with additionalContext
python3 -c "
import json, sys
ctx = '\U0001f4ec New messages:' + '$SUMMARY' + '\n\n(Use comms_read for full history, comms_send to reply)'
print(json.dumps({
    'hookSpecificOutput': {
        'hookEventName': 'PostToolUse',
        'additionalContext': ctx
    }
}))
"
